---
- name: EC2 Apache Web Server Setup
  hosts: ec2
  become: true
  tasks:

    - name: Update all packages
      amazon.aws.yum:
        name: "*"
        state: latest

    - name: Stop Nginx if running
      systemd:
        name: nginx
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove Nginx if installed
      yum:
        name: nginx
        state: absent
      ignore_errors: yes

    - name: Install Apache HTTPD
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache HTTPD
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Get IMDSv2 token
      uri:
        url: http://169.254.169.254/latest/api/token
        method: PUT
        headers:
          X-aws-ec2-metadata-token-ttl-seconds: "21600"
        return_content: yes
      register: imds_token

    - name: Get public IP
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        method: GET
        headers:
          X-aws-ec2-metadata-token: "{{ imds_token.content }}"
        return_content: yes
      register: public_ip

    - name: Get public hostname
      uri:
        url: http://169.254.169.254/latest/meta-data/public-hostname
        method: GET
        headers:
          X-aws-ec2-metadata-token: "{{ imds_token.content }}"
        return_content: yes
      register: public_hostname

    - name: Show public IP
      debug:
        msg: "Public IP of EC2 instance: {{ public_ip.content }}"

    - name: Restart Apache HTTPD
      systemd:
        name: httpd
        state: restarted

